# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.3
loom_version=1.14-SNAPSHOT
# Mod Properties
mod_version=1.0.15
maven_group=com.gitsh01.libertyvillagers
archives_base_name=liberty-villagers-mod
# Dependencies
fabric_version=0.138.4+1.21.10
mod_menu_version=16.0.0-rc.1
cloth_config_version=15.0.127
server_translations_version=2.5.2+1.21.9-pre3
min_server_translations_version=2.5.2+1.21.9-pre3
# Publishing
modrinth_id=264clomZ
curseforge_id=700485
debug_publishing=false
modrinth_required=fabric-api
modrinth_optional=modmenu
curseforge_versions=1.21.10
cf_requirements=fabric-api
cf_optionals=server-translation-api; modmenu
release_type=release
#Other
mod_gradle_scripts_ref=1.1.12
GITHUB_ACTOR=gitsh01
changelog_url=''
